controllerManager:
  webhook:
    command:
    - /manager
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: example.com/ovn-kubernetes-resource-injector
      tag: v0.1.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  hostNetwork: false
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: "Exists"
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: NoSchedule
resourceName: ""
nadName: dpf-ovn-kubernetes
# -- The label that indicates a node has a DPU, runs OVNK in dpu-host mode and needs VF injection.
# Format: key=value
dpuHostLabel: k8s.ovn.org/dpu-host=
# -- When enabled, injects VFs when pod selectors match both nodes with and without the DPU label, in case both such
# nodes exist in the cluster.
# In either case, the admin needs to ensure that they have sufficient amount of workers with DPU (when enabled)
# or without DPU (when disabled) so that Pods can fit in case the selectors match both types of nodes.
# Note that when disabled the webhook may inject additional affinity to ensure Pods land on the correct nodes.
prioritizeOffloading: true
